name: Publish Package to TestPyPI

# do not run automatically until git workflow (developing on 'develop' branch) has been established
# on: push
on: workflow_dispatch

jobs:
  build-n-publish:
    name: Build and publish package to TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@test-publish-bug
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish EAO to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
